### ISSUE TITLE
Unable to install the app in this location

### ISSUE THREAD

**Issue by enesaydogan** [YunoHost-Apps/collaboraonline_ynh#1]
![ekran alintisi](https://user-images.githubusercontent.com/20522050/28994268-8bbbd21a-79d2-11e7-9066-20c4c9eedf1e.PNG)

> Installation failed
> The SSOwat configuration has been generated
> + sudo service nginx reload
> + sudo rm -f /etc/nginx/conf.d/.d/collabora.conf
> + sudo rm -rf /var/www/collabora
> + domain=
> ++ sudo yunohost app setting collabora domain --output-as plain --quiet
> ++ ynh_app_setting_get collabora domain
> ++ . /usr/share/yunohost/helpers.d/utils
> ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/user
> ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/system
> ++ '[' -r /usr/share/yunohost/helpers.d/system ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/string
> ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/setting
> ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/print
> ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/package
> ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/network
> ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
> ++ . /usr/share/yunohost/helpers.d/mysql
> ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/ip
> ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ CAN_BIND=1
> ++ . /usr/share/yunohost/helpers.d/filesystem
> ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/backend
> ++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ run-parts --list /usr/share/yunohost/helpers.d
> + source /usr/share/yunohost/helpers
> + app=collabora
> Executing script '/var/cache/yunohost/from_file/collaboraonline_ynh-master/scripts/remove'...
> Path not available: depo.sinanergrup.com.tr
> + exit 1
> + echo 'Path not available: depo.sinanergrup.com.tr'
> + ynh_die 'Path not available: depo.sinanergrup.com.tr'
> Unable to install the app in this location
> 'yunohost app checkurl' is deprecated and will be removed in the future
> + sudo yunohost app checkurl depo.sinanergrup.com.tr -a collabora
> + sudo yunohost app setting collabora is_public -v 1 --quiet
> + ynh_app_setting_set collabora is_public 1
> + source _common.sh
> ++ . /usr/share/yunohost/helpers.d/utils
> ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/user
> ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/system
> ++ '[' -r /usr/share/yunohost/helpers.d/system ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/string
> ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/setting
> ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/print
> ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/package
> ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/network
> ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
> ++ . /usr/share/yunohost/helpers.d/mysql
> ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/ip
> ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ CAN_BIND=1
> ++ . /usr/share/yunohost/helpers.d/filesystem
> ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++ . /usr/share/yunohost/helpers.d/backend
> ++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
> ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ run-parts --list /usr/share/yunohost/helpers.d
> + source /usr/share/yunohost/helpers
> + is_public=1
> + domain=depo.sinanergrup.com.tr
> + app=collabora
> + set -eu
> Executing script '/var/cache/yunohost/from_file/collaboraonline_ynh-master/scripts/install'...

**Comment by frju365** [comment]
Apparently, it's because your domain has already an app on it.
