### ISSUE TITLE
Can't install app

### ISSUE THREAD

**Issue by brogen67** [YunoHost-Apps/collaboraonline_ynh#2]
Hi, 

Impossible for me to install app.

**2017-08-22 13:33:38,968 WARNING  yunohost.hook <lambda> - [470.135] W: Size of file /var/lib/apt/lists/partial/collaboraoffice.com_repos_CollaboraOnline_CODE-debian8_._Packages.bz2 is not what the server reported 8005 373**
[...]
2017-08-22 13:33:39,865 INFO     yunohost.hook <lambda> - [470.135] + ynh_nginx_config
**2017-08-22 13:33:39,866 WARNING  yunohost.hook <lambda> - [470.135] ./install: line 65: ynh_nginx_config: command not found**

**Comment by frju365** [comment]
I did a PR. Normally it solves the problem of the command not found. But I need to wait before merging it.

**Comment by brogen67** [comment]
Thanks for your help, but it doesn't resolve the problem : 

Now i have  :
_common.sh: line 32: ynh_store_checksum_config: command not found
