### ISSUE TITLE
Install fails - 'Path not available'

### ISSUE THREAD

**Issue by steveowashere** [YunoHost-Apps/collaboraonline_ynh#4]
Hello, I believe I am having the same issue as #1 . I can't seem to install the app no mater what path I choose. As you can see in the [log](https://spooknik.site/zerobin/?6a95049addc81228#enVT0PKMROZAPRS8146aRF5pP7+WqmrYrAo1+A5IMHM=), i've chosen a totally random path that's never been used before, but the install still failed. I've never installed Collabora before on this sever and it's a fresh install. 

Thanks for any help on this!

**Comment by Rafi594** [comment]
Hi

You can't install this app in a sub path you can use a sub domain or a dedicated domain for Collabora

I added a warning when installing Collabora

**Comment by JimboJoe** [comment]
... or you can just ask for domain (and not path) at installation 😉

**Comment by steveowashere** [comment]
Thanks for the reply and updating. 

Unfortunately,  even after using a sub-domain and not using a subpath, the [install still fails](https://spooknik.site/zerobin/?aa1f2e4940f0fd88#bvSlGBWTjfS3q/4lUK9ztIszQ0iU2QyIi7d8E0AGTj0=). Not sure what gives.

**Comment by steveowashere** [comment]
Had a little time to dig through the log, this error now pops up: 

`Warning: Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.`

Running` systemctl status nginx.service`

Gives me: 

`Sep 04 17:54:30 spooknik.site nginx[15134]: nginx: [emerg] location "/loleaflet" is outside location "__PATH__" in /etc/nginx/conf.d/office.spooknik.site.d/collabora.conf:4
Sep 04 17:54:30 spooknik.site systemd[1]: nginx.service: control process exited, code=exited status=1
Sep 04 17:54:30 spooknik.site systemd[1]: Reload failed for A high performance web server and a reverse proxy server.`

So this is most likely the problem. but i'm not totally sure how to fix it.

**Comment by Rafi594** [comment]
This app have a problem with the nginx config

I will look for this

**Comment by steveowashere** [comment]
Thanks again for the update. It now says: 

`Error: Requirements are not met, the package yunohost (2.7.2) must be >> 2.7.2`

I believe line 17 in manifest.json should be: 

        "yunohost": ">= 2.7.2"

I created a pull request to fixed this. So the script doesn't fail on this anymore. 
However, it is still failing on the nginx config. 

It's giving the message: 

`Sep 05 12:50:58 spooknik.site nginx[2981]: nginx: [emerg] location "/loleaflet" is outside location "office.spooknik.site" in /etc/nginx/conf.d/office.spooknik.site.d/collabora.conf:4`

`Sep 05 12:50:58 spooknik.site systemd[1]: nginx.service: control process exited, code=exited status=1`

`Sep 05 12:50:58 spooknik.site systemd[1]: Reload failed for A high performance web server and a reverse proxy server.`
